---

- name: Install Prometheus Server
  yum:
    name: prometheus
    state: present

- name: copy Prometheus config to server
  template: src=prometheus.yml.j2 dest=/etc/prometheus/prometheus.yaml
  notify: 
    - restart prometheus

- name: Enable Prometheus 
  service: name=prometheus enabled=yes

